### PR TITLE
Add hooks to genkernel

### PR DESCRIPTION
**Pull request by Dissonant-Tech**
Possible solution to #61

### CODE REVIEW

**Comment by mudler** [comment]
Thanks! i like the idea of having configurable hooks, and i ack for completeness: if we have to provide this feature should be complete in each phase (as you did).

But i do think that needs to be documented (since we already lack it in some areas)

**Comment by Dissonant-Tech** [comment]
> But i do think that needs to be documented

@mudler Not a problem! I'm taking a look at `doc/genkernel.8.txt` to see where the docs would fit but I'm not too sure. Should there be a new category or under an old one? And if so, where would that category fit?

From what I can tell the best places would either be:

1. `HOOKS` category between `ACTIONS` and `OPTIONS`
2. `HOOKS` category before `NETBOOTING`
3. Documentation under `ACTIONS` since the available actions correlate pretty well with the available hooks.

In any case it will consist of a bit of info on how the hooks work (running all executable scripts in a certain directory) plus a list of available hooks. 

Just let me know what sounds best and I'll get on that.

**Comment by mudler** [comment]
to me looks fine either way 👍  , feel free to pick one - even tho i'm inclined for 2) since it's a new feature, but 3) sounds also fair as well

**Comment by Dissonant-Tech** [comment]
@mudler I ended up going for 2) as suggested, and in the end I think it was the right option. Let me know if you feel there is anything else missing.

**Comment by mudler** [comment]
Thanks! 👍

**Pull request merged**
